### ISSUE TITLE
Two morons shooting each other for more than 5 minutes

### ISSUE THREAD

**Issue by bocianu** [pkali/scorch_src#35]
![image](https://user-images.githubusercontent.com/2974998/162632979-97397069-43f4-4c7a-9827-494df9eae323.png)

Two CPU guys in positions like on the picture above shoot each other for over 5 minutes until finally guy on left won. 
Not a bug at all, but it stops interaction for a long time. 
At parties in can be The Fun Killer.

Maybe there should be an option to finish the round earlier somehow?

**Comment by pkali** [comment]
good idea. I can also deduct more energy with each shoot, but this would change the tactics :]

**Comment by ehn-pkalinowski** [comment]
I've recalled an old fix where I specifically had made morons shoot themselves less often :] 
The problem is still the same for 2 better computer opponents, the game might end quicker, but it is not guaranteed. 
The best idea, for now, is some kind of disaster that reduces the energy of all players, so all but the best die (to preserve wins).

**Comment by ehn-pkalinowski** [comment]
I could do sth like in many old games - an additional enemy like a plane bombarding the playfield when no hits for a number of rounds.

**Comment by pkali** [comment]
build 135
