### ISSUE TITLE
tank says goodbye when invisible

### ISSUE THREAD

**Issue by bocianu** [pkali/scorch_src#63]
This is not a bug, it is more "User Experience" issue.
When players gets killed it says it's last "goodbye" sentence, 
but when the message shows on the screen, the tank is already invisible. 

I think it should disappear AFTER the farewell. 
Maybe toegether with the sentence?

**Comment by pkali** [comment]
'tis ain't no easy, man. but we'll try our best :]

**Comment by pkali** [comment]
OK, so I did some code analysis and the result is that this change is surprisingly difficult. This is because the whole logic of the disappearing tank is somewhat reversed - all tanks disappear and then only those still alive reappear. This is governed in a completely different place from displaying these goodbye texts. Right now I must postpone this issue, maybe @Pecusx will have a better idea of how to do it?

**Comment by pkali** [comment]
Just wanted to add that although this is basically a non-issue when you kill a single tank, it is a pain when you drop a large weapon, destroy 3 tanks and they talk for a long while from the nothingness...

**Comment by pkali** [comment]
I call it done in 142 - it is not perfect, but as good as it gets without a heavy rewrite - now tanks say goodbye when visible. This fails when many tanks has been destroyed and some dying weapons cleared the area. Still better than it was.
